import React from 'react'
import Head from "next/head";
import AnimatedText from "@/components/AnimatedText";
import Contact from '@/components/Contact';
import TransitionEffect from '@/components/TransitionEffect';

const contactus = () => {
  return (
    

    <>
    
    <Head>
        <title>Itriangle | Contact Us</title>
        <meta name="Itriangle" content="Generated by create next app" />
      </Head>
      <AnimatedText
        text="To Know More About The Services We Offer."
        className="mb-16 lg:!text-7xl sm:mb-8 sm:!text-6xl xs:!text-4xl"

      />
      {/* <TransitionEffect/> */}

      <Contact/>
    
    
    </>


  )
}

export default contactus