import React from "react";
import Head from "next/head";
import AnimatedText from "@/components/AnimatedText";
import Contact from "@/components/Contact";
import TransitionEffect from "@/components/TransitionEffect";
import Layout from "@/components/Layout";

const contactus = () => {
  return (
    <>
      <Head>
        <title>ITrian | Contact Us</title>
        <meta name="ITrian" content="Generated by create next app" />
      </Head>
      <AnimatedText
        text="To Know More About The Services We Offer."
        className="mb-16 lg:!text-7xl sm:mb-8 sm:!text-6xl xs:!text-4xl"
      />

      <main className="flex w-full flex-col items-center justify-center dark:text-light">
        <Layout className="pt-16">
          <div className="grid w-full grid-cols-10 gap-16 sm:gap-8">
            <div className="col-span-4 flex flex-col items-start justify-start xl:col-span-4 md:order-2 md:col-span-8">
            <h2 className="mb-10 text-lg font-bold uppercase text-dark/75 dark:text-light/75">
            Why Should You Contact Us ?..
          </h2>
              <p className="font-medium text-lg mb-5">
                Let’s Build Something Extraordinary <br></br> Together Got a
                project in mind? Need a partner to elevate your digital
                presence? We’re just a message away.
              </p>

              <p className="font-medium text-lg mt-4">
                Get in Touch <br></br> We’d love to hear from you! Whether you
                have a question, need a consultation, or are ready to start your
                next big project, our team is here to help.
              </p>
            </div>
            <div
              className="col-span-6 relative h-max rounded-2xl border-2 border-solid border-dark 
            bg-light p-8 dark:bg-dark dark:border-light xl:col-span-4 md:order-1 md:col-span-8"
            >
              <div className="absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark dark:bg-light" />
              <Contact />
            </div>
          </div>
        </Layout>
      </main>

      {/* <TransitionEffect/> */}
    </>
  );
};

export default contactus;
