import React from "react";
import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "@/components/TransitionEffect";


export default function Home() {
  return (
    <>
      <Head>
        <title>ITrian</title>
        <meta name="ITrian" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex flex-col items-center justify-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:p-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col mb-32">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="ChamudithBandara"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw,
                (max-width: 1200px) 50vw,
                50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Shaping the Future of Business with Tech & Strategy"
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                From cutting-edge web development to ROI-driven digital
                strategies, we craft solutions that elevate your brand, boost
                growth, and deliver results.
              </p>
            </div>
          </div>
        </Layout>

        <HireMe />

        <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image
            src={lightBulb}
            alt="ChamudithBandara"
            className="w-full h-auto"
          />
        </div>
      </main>
    </>
  );
}
