import React, { useEffect, useRef } from "react";
import { useInView, useMotionValue, useSpring } from "framer-motion";
import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import profilePic2 from "../../public/images/profile/developer-pic-2.jpg";
import AnimatedText from "@/components/AnimatedText";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "@/components/TransitionEffect";
import Experience from "@/components/Experience";
import Skills from "@/components/Skills";

const AnimatedNumbers = ({ value }) => {
  const ref = useRef(null);

  const motionValue = useMotionValue(0);
  const springValue = useSpring(motionValue, { duration: 3000 });
  const isInView = useInView(ref, { once: true });

  useEffect(() => {
    if (isInView) {
      motionValue.set(value);
    }
  }, [isInView, value, motionValue]);

  useEffect(() => {
    springValue.on("change", (latest) => {
      if (ref.current && latest.toFixed(0) <= value) {
        ref.current.textContent = latest.toFixed(0);
      }
    });
  }, [springValue, value]);

  return <span ref={ref} />;
};

export default function Home() {
  return (
    <>
      <Head>
        <title>ITrian</title>
        <meta name="ITrian" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex flex-col items-center justify-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:p-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col mb-32">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="ChamudithBandara"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw,
                (max-width: 1200px) 50vw,
                50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Shaping the Future of Business with Tech & Strategy"
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                From cutting-edge web development to ROI-driven digital
                strategies, we craft solutions that elevate your brand, boost
                growth, and deliver results.
              </p>
            </div>
          </div>

          <AnimatedText
            text="About Us!"
            className="mb-16 !text-7xl lg:!text-5xl sm:!text-6xl xs:!text-4xl sm:mb-8"
          />

          <div className="container mx-auto px-4 py-16">
            <div className="grid w-full grid-cols-8 gap-16 sm:gap-8">
              <div className="col-span-3 flex flex-col items-start justify-start xl:col-span-4 md:order-2 md:col-span-8">
                <h1 className="mb-6 text-3xl font-extrabold uppercase text-dark dark:text-light">
                  About Us
                </h1>

                <h2 className="mb-4 text-lg font-bold uppercase text-dark/75 dark:text-light/75">
                  Who We Are
                </h2>
                <p className="font-medium">
                  At Itrian, we are a team of passionate innovators,
                  strategists, and problem-solvers committed to transforming
                  businesses in the digital age. With expertise in software
                  development and digital marketing, we combine cutting-edge
                  technology with data-driven strategies to deliver scalable
                  solutions tailored to your unique goals.
                </p>

                

                
              </div>

              <div className="col-span-3 relative h-max rounded-2xl border-2 border-solid border-dark bg-light p-8 dark:bg-dark dark:border-light xl:col-span-4 md:order-1 md:col-span-8">
                <div className="absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark dark:bg-light" />
                <Image
                  src={profilePic2}
                  alt="Itrian Team"
                  className="w-full h-auto rounded-2xl"
                  priority
                />
              </div>

              <div className="col-span-2 flex flex-col items-end justify-between xl:col-span-8 xl:flex-row xl:items-center md:order-3">
                <div className="flex flex-col items-end justify-center xl:items-center">
                  <span className="inline-block text-7xl font-bold md:text-6xl sm:text-5xl xs:text-4xl">
                    <AnimatedNumbers value={15} />+
                  </span>
                  <h2 className="text-xl font-medium capitalize text-dark/75 dark:text-light/75 xl:text-center md:text-lg sm:text-base xs:text-sm">
                    Satisfied Clients
                  </h2>
                </div>

                <div className="flex flex-col items-end justify-center xl:items-center">
                  <span className="inline-block text-7xl font-bold md:text-6xl sm:text-5xl xs:text-4xl">
                    <AnimatedNumbers value={13} />+
                  </span>
                  <h2 className="text-xl font-medium capitalize text-dark/75 dark:text-light/75 xl:text-center md:text-lg sm:text-base xs:text-sm">
                    Projects Completed
                  </h2>
                </div>

                <div className="flex flex-col items-end justify-center xl:items-center">
                  <span className="inline-block text-7xl font-bold md:text-6xl sm:text-5xl xs:text-4xl">
                    <AnimatedNumbers value={2} />+
                  </span>
                  <h2 className="text-xl font-medium capitalize text-dark/75 dark:text-light/75 xl:text-center md:text-lg sm:text-base xs:text-sm">
                    Years of Experience
                  </h2>
                </div>
              </div>
            </div>
          </div>

          <h2 className="mt-6 text-lg font-bold uppercase text-dark/75 dark:text-light/75">
                  What We Do
                </h2>
                <p className="my-4 font-medium">
                  We specialize in crafting dynamic websites, robust
                  applications, and comprehensive marketing campaigns that drive
                  growth and maximize ROI. Whether you're looking for custom web
                  and mobile app development, seamless e-commerce solutions, or
                  impactful digital marketing strategies like SEO, PPC, and
                  social media, we’re here to help you succeed.
                </p>

                <ul className="list-disc pl-6 font-medium">
                  <li>
                    Custom-Built: Designed to match your specific business
                    needs.
                  </li>
                  <li>
                    Future-Ready: Leveraging the latest technology and market
                    trends.
                  </li>
                  <li>
                    Results-Driven: Focused on measurable outcomes that matter
                    to you.
                  </li>
                </ul>

          <h2 className="mt-6 text-lg font-bold uppercase text-dark/75 dark:text-light/75">
                  Our Mission
                </h2>
                <p className="font-medium">
                  To empower businesses by delivering innovative solutions that
                  combine technology and creativity, enabling them to thrive in
                  an ever-evolving digital landscape.
                </p>

                <h2 className="mt-6 text-lg font-bold uppercase text-dark/75 dark:text-light/75">
                  Our Vision
                </h2>
                <p className="font-medium">
                  To be the trusted partner for businesses worldwide, setting
                  benchmarks in software innovation and marketing excellence.
                </p>

                <h2 className="mt-6 text-lg font-bold uppercase text-dark/75 dark:text-light/75">
                  Why Choose Us?
                </h2>
                <ul className="list-disc pl-6 font-medium">
                  <li>
                    End-to-End Expertise: From idea to execution, we handle
                    everything.
                  </li>
                  <li>
                    Collaborative Approach: We work closely with our clients to
                    ensure their vision is realized.
                  </li>
                  <li>
                    Data-Driven Results: Every decision we make is backed by
                    analytics and industry insights.
                  </li>
                  <li>
                    Scalable Solutions: As your business grows, our solutions
                    grow with you.
                  </li>
                </ul>

          <Experience />
          <Skills />
        </Layout>

        <HireMe />

        <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image
            src={lightBulb}
            alt="ChamudithBandara"
            className="w-full h-auto"
          />
        </div>
      </main>
    </>
  );
}
