import React from "react";
import Head from "next/head";
import AnimatedText from "@/components/AnimatedText";
import TransitionEffect from "@/components/TransitionEffect";
import Service from "@/components/Service";
import Layout from "@/components/Layout";

const servicepage = () => {
  return (
    <>
      <Head>
        <title>ITrian | Services</title>
        <meta name="ITrian" content="Generated by create next app" />
      </Head>
      <AnimatedText
        text="Our Services"
        className="mb-16 lg:!text-7xl sm:mb-8 sm:!text-6xl xs:!text-4xl"
      />
      {/* <TransitionEffect/> */}

      <main className="flex w-full flex-col items-center justify-center dark:text-light">
        <Layout className="pt-8">
          <h2 className="mb-10 text-lg font-bold uppercase text-dark/75 dark:text-light/75">
            What Is Our Services !..
          </h2>
          <p className="font-medium text-lg">
            At Itrian, we offer a full spectrum of services designed to help
            your business thrive in the digital age. From cutting-edge software
            development to ROI-focused marketing strategies, we’re here to make
            your vision a reality.
          </p>
        </Layout>
      </main>

      <Service />
    </>
  );
};

export default servicepage;
