import React from 'react'
import Head from "next/head";
import AnimatedText from "@/components/AnimatedText";
import TransitionEffect from '@/components/TransitionEffect';
import Service from '@/components/Service';

const servicepage = () => {
  return (
    <>

<Head>
        <title>ITrian | Contact Us</title>
        <meta name="ITrian" content="Generated by create next app" />
      </Head>
      <AnimatedText
        text="Our Services"
        className="mb-16 lg:!text-7xl sm:mb-8 sm:!text-6xl xs:!text-4xl"

      />
      

      <Service/>

    </>
  )
}

export default servicepage